'use client';

import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { siteContentApi, type AboutContent } from '@/services/siteContentApi';

const field = 'mt-1 block min-h-10 w-full rounded-xl border border-[#cbd6ef] bg-white px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-primary';
const label = 'block text-sm font-semibold text-[#334166]';

function AssetPicker({ title, assetId, onSelected }: { title: string; assetId: string | null; onSelected: (id: string) => void }) {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const upload = async () => {
    if (!file) return;
    setBusy(true);
    try { const asset = await siteContentApi.uploadAsset(file); onSelected(asset.id); toast.success('Ảnh đã tải lên. Lưu bản nháp để gắn ảnh vào trang.'); }
    catch (error) { toast.error(error instanceof Error ? error.message : 'Không thể tải ảnh.'); }
    finally { setBusy(false); }
  };
  return <div className="space-y-2 rounded-xl border border-[#dbe3fa] bg-[#f8faff] p-4"><p className="text-sm font-bold text-[#172554]">{title}</p>{preview && <div role="img" aria-label="Xem trước ảnh vừa chọn" className="h-44 max-w-sm rounded-lg bg-cover bg-center" style={{ backgroundImage: `url("${preview}")` }} />}{assetId && <p className="break-all text-xs text-[#52617e]">Asset ID đã chọn: {assetId}</p>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const next = event.target.files?.[0] || null; setFile(next); setPreview(next ? URL.createObjectURL(next) : null); }} className="block w-full text-xs" /><button type="button" disabled={!file || busy} onClick={() => void upload()} className="min-h-9 rounded-lg border border-primary px-3 text-xs font-bold text-primary disabled:opacity-50">{busy ? 'Đang tải...' : 'Tải ảnh và chọn'}</button></div>;
}

export function AboutEditor({ value, onChange }: { value: AboutContent; onChange: (next: AboutContent) => void }) {
  const set = <K extends keyof AboutContent>(key: K, next: AboutContent[K]) => onChange({ ...value, [key]: next });
  const updateValue = (index: number, key: 'title' | 'description' | 'iconKey', next: string) => set('values', value.values.map((item, at) => at === index ? { ...item, [key]: next } : item));
  const updateMilestone = (index: number, key: 'label' | 'title' | 'description', next: string) => set('milestones', value.milestones.map((item, at) => at === index ? { ...item, [key]: next } : item));
  const updateMember = (index: number, key: 'name' | 'role' | 'bio' | 'assetId', next: string | null) => set('teamMembers', value.teamMembers.map((item, at) => at === index ? { ...item, [key]: next } : item));
  return <div className="space-y-8">
    <section className="grid gap-4 md:grid-cols-2"><h3 className="text-lg font-bold text-[#172554] md:col-span-2">Hero</h3><label className={label}>Tiêu đề<input value={value.heroTitle} maxLength={160} onChange={(e) => set('heroTitle', e.target.value)} className={field} /></label><label className={label}>Mô tả<textarea value={value.heroSubtitle} maxLength={500} rows={3} onChange={(e) => set('heroSubtitle', e.target.value)} className={field} /></label><div className="md:col-span-2"><AssetPicker title="Ảnh hero" assetId={value.heroAssetId} onSelected={(id) => set('heroAssetId', id)} /></div></section>
    <section className="grid gap-4 md:grid-cols-2"><h3 className="text-lg font-bold text-[#172554] md:col-span-2">Sứ mệnh</h3><label className={label}>Tiêu đề<input value={value.missionTitle} maxLength={160} onChange={(e) => set('missionTitle', e.target.value)} className={field} /></label><label className={label}>Nội dung<textarea value={value.missionBody} maxLength={3000} rows={5} onChange={(e) => set('missionBody', e.target.value)} className={field} /></label><div className="md:col-span-2"><AssetPicker title="Ảnh sứ mệnh" assetId={value.missionAssetId} onSelected={(id) => set('missionAssetId', id)} /></div></section>
    <section className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-[#172554]">Giá trị cốt lõi</h3><button type="button" disabled={value.values.length >= 6} className="text-sm font-bold text-primary disabled:opacity-40" onClick={() => set('values', [...value.values, { title: '', description: '', iconKey: null }])}>+ Thêm giá trị</button></div>{value.values.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border border-[#dbe3fa] p-4 md:grid-cols-2"><label className={label}>Tiêu đề<input value={item.title} maxLength={100} onChange={(e) => updateValue(index, 'title', e.target.value)} className={field} /></label><label className={label}>Icon key (tùy chọn)<input value={item.iconKey || ''} maxLength={40} onChange={(e) => updateValue(index, 'iconKey', e.target.value)} className={field} /></label><label className={`${label} md:col-span-2`}>Mô tả<textarea value={item.description} maxLength={500} rows={2} onChange={(e) => updateValue(index, 'description', e.target.value)} className={field} /></label><button type="button" onClick={() => set('values', value.values.filter((_, at) => at !== index))} className="justify-self-start text-xs text-red-700 underline">Xóa mục này</button></div>)}</section>
    <section className="space-y-4"><div className="flex items-center justify-between"><h3 className="text-lg font-bold text-[#172554]">Cột mốc thật</h3><button type="button" disabled={value.milestones.length >= 20} className="text-sm font-bold text-primary disabled:opacity-40" onClick={() => set('milestones', [...value.milestones, { label: '', title: '', description: '' }])}>+ Thêm cột mốc</button></div><p className="text-xs text-[#52617e]">Chỉ nhập mốc đã được xác nhận. Mặc định không có cột mốc.</p>{value.milestones.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border border-[#dbe3fa] p-4 md:grid-cols-2"><label className={label}>Nhãn<input value={item.label} maxLength={100} onChange={(e) => updateMilestone(index, 'label', e.target.value)} className={field} /></label><label className={label}>Tiêu đề<input value={item.title} maxLength={160} onChange={(e) => updateMilestone(index, 'title', e.target.value)} className={field} /></label><label className={`${label} md:col-span-2`}>Mô tả<textarea value={item.description} maxLength={500} rows={2} onChange={(e) => updateMilestone(index, 'description', e.target.value)} className={field} /></label><button type="button" onClick={() => set('milestones', value.milestones.filter((_, at) => at !== index))} className="justify-self-start text-xs text-red-700 underline">Xóa mục này</button></div>)}</section>
    <section className="space-y-4"><h3 className="text-lg font-bold text-[#172554]">Đội ngũ</h3><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={value.teamSectionEnabled} onChange={(e) => set('teamSectionEnabled', e.target.checked)} /> Hiện đội ngũ khi có dữ liệu thật</label>{value.teamSectionEnabled && <><label className={label}>Tiêu đề đội ngũ<input value={value.teamHeading || ''} maxLength={160} onChange={(e) => set('teamHeading', e.target.value || null)} className={field} /></label><button type="button" disabled={value.teamMembers.length >= 20} onClick={() => set('teamMembers', [...value.teamMembers, { name: '', role: '', bio: null, assetId: null }])} className="text-sm font-bold text-primary disabled:opacity-40">+ Thêm thành viên thật</button>{value.teamMembers.map((member, index) => <div key={index} className="grid gap-3 rounded-xl border border-[#dbe3fa] p-4 md:grid-cols-2"><label className={label}>Tên<input value={member.name} maxLength={120} onChange={(e) => updateMember(index, 'name', e.target.value)} className={field} /></label><label className={label}>Vai trò<input value={member.role} maxLength={120} onChange={(e) => updateMember(index, 'role', e.target.value)} className={field} /></label><label className={`${label} md:col-span-2`}>Giới thiệu<textarea value={member.bio || ''} maxLength={500} rows={2} onChange={(e) => updateMember(index, 'bio', e.target.value || null)} className={field} /></label><div className="md:col-span-2"><AssetPicker title={`Ảnh của ${member.name || 'thành viên'}`} assetId={member.assetId} onSelected={(id) => updateMember(index, 'assetId', id)} /></div><button type="button" onClick={() => set('teamMembers', value.teamMembers.filter((_, at) => at !== index))} className="justify-self-start text-xs text-red-700 underline">Xóa thành viên</button></div>)}</>}</section>
  </div>;
}
